### ISSUE TITLE
Shares ownership and transfer

### ISSUE THREAD

**Issue by babeanu-dorian** [babeanu-dorian/AssetShare#3]
Develop an aragon app that keeps track of a list of owners, their shares, and allows them to transfer shares to one another for money. Requirements:
 - The app knows how many shares each owner has
 - Owners can offer shares to be sold
 - The application handles both the money transfer and the shares transfer
 - An owner cannot sell more auctions than they have available (owned and not offered for sale)
 - An offer owner can cancel their own offer(s)
 - Only the owner of an offer can cancel it
 - When someone purchases shares from a sell offer, they have to transfer the exact amount asked
 - If a transaction fails due to unmet conditions, no money or shares should be transferred or lost (use 'require' instead of 'if' where appropriate)
 - Total number of shares in the app should stay constant

**Comment by Pieter12345** [comment]
A clarification on how I believe the buy/sell system should work:
### Selling shares
A shareholder can put up their shares for sale at a given Ether/Share price. If there are buy offers which offer this price or higher, then the seller gets the price for which the buyer(s) wanted to buy the shares. If there are multiple buyers, then they are handled from highest to lowest offer. If the seller hasn't sold all their shares immediately, the remaining shares stay up for sale.

### Buying shares
Anyone can put in a buy offer for shares at a given Ether/Share price. If there are sell offers for this price or less, then the buyer gets the shares for the price asked by the seller(s). If there are multiple sellers, then they are handled from lowest to highest price. If the buyer hasn't bought all their shares immediately, the remaining offer for shares stays up.

### Reasoning
If 5 shares are up for sale from different sellers for 1, 3, 3, 2 and 5 Ether, then a buyer could just put in a request to buy 6 shares for 5 Ether each and buy the first 5 instantly for 14 Ether. As soon as another sell offer for <=5 Ether would come in, the buyer would get his last share, given that there's no higher buyer in the system. A similar example happens with a seller immediately selling (a part of) their shares. If the price of the seller or buyer is always used, then it means that a seller or buyer has to put in multiple offers at those exact prices to sell/buy their shares for the best price. This becomes a burden when considering transactions involving many shares.
