### ISSUE TITLE
Testing (theory)

### ISSUE THREAD

**Issue by babeanu-dorian** [babeanu-dorian/AssetShare#4]
Look into how to test our aragon app

**Comment by Pieter12345** [comment]
Aragon does not offer a guide or documentation on testing. However, [this test](https://github.com/aragon/aragon-react-boilerplate/blob/master/test/app.js) in the React boilerplate project template tests [this contract](https://github.com/aragon/aragon-react-boilerplate/blob/master/contracts/CounterApp.sol), so we should use this as a good example. Aragon uses Truffle to run all tests in the `test` directory at the root of the project. Truffle's documentation can be found [here](https://www.trufflesuite.com/docs/truffle/testing/testing-your-contracts). Running tests can be done using `npm test`, which indirectly calls Truffle.
